# Generated by Django 3.2.19 on 2023-06-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230504_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='confidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'confidence',
            },
        ),
        migrations.CreateModel(
            name='confidencename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'confidence_name',
            },
        ),
        migrations.CreateModel(
            name='confidenceindicatorset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('confidences', models.ManyToManyField(to='api.Confidence')),
            ],
            options={
                'db_table': 'confidence_indicator_sets',
            },
        ),
        migrations.AddField(
            model_name='confidence',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.confidencename'),
        ),
    ]
