# Generated by Django 3.2.19 on 2023-06-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230605_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationcampaign',
            name='confidence_indicator_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.confidenceindicatorset'),
        ),
        migrations.AddField(
            model_name='annotationresult',
            name='confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.confidence'),
        ),
    ]
