# Generated by Django 3.2.19 on 2023-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20230605_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidenceindicatorset',
            name='default_confidence',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=models.deletion.CASCADE,
                                    related_name='default_confidence',
                                    to='api.confidence'),
        ),
    ]
