# Generated by Django 3.2.21 on 2023-10-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_change_zoom_level_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationcampaign",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dataset",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
