# Generated by Django 3.2.19 on 2023-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_confidenceindicatorset_defaultcondidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidenceindicatorset',
            name='confidences',
            field=models.ManyToManyField(to='api.Confidence'),
        ),
        migrations.AlterModelTable(
            name='confidenceindicatorset',
            table='confidence_sets',
        ),
    ]
