# Generated by Django 3.2.19 on 2023-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230607_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidenceindicatorset',
            name='confidences',
            field=models.ManyToManyField(to='api.Confidence'),
        ),
    ]
